"""
ArtifactCard component — single artifact with diff preview.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass
from enum import Enum

from textual.app import ComposeResult
from textual.message import Message
from textual.reactive import reactive
from textual.widget import Widget
from textual.widgets import Static


class ArtifactState(Enum):
    CREATED = "created"
    MODIFIED = "modified"
    DELETED = "deleted"


@dataclass
class Artifact:
    """A single file artifact generated by the agent."""

    path: str
    state: ArtifactState
    timestamp: datetime.datetime
    diff_lines: list[str] = None
    preview: str = ""

    def __post_init__(self) -> None:
        if self.diff_lines is None:
            self.diff_lines = []


class ArtifactCard(Widget):
    """
    Single artifact card showing file path, state, and optional diff.

    Layout:
    ┌─ path ──────────────────────────────── state  N min ago ───┐
    │  3 lines changed                                         │
    │  ┌─ diff ──────────────────────────────────────────────┐ │
    │  │- old line                                         │ │
    │  │+ new line                                         │ │
    │  └──────────────────────────────────────────────────┘ │
    │  [jump] [diff] [copy path]                             │
    └────────────────────────────────────────────────────────┘
    """

    artifact: reactive[Artifact | None] = reactive(None)

    class JumpToFile(Message, bubble=True):
        """User clicked jump-to-file."""

        def __init__(self, path: str) -> None:
            super().__init__()
            self.path = path

    class ShowDiff(Message, bubble=True):
        """User clicked show-diff."""

        def __init__(self, path: str) -> None:
            super().__init__()
            self.path = path

    def __init__(self, artifact: Artifact | None = None) -> None:
        super().__init__()
        self._artifact = artifact

    def compose(self) -> ComposeResult:
        yield Static("", id="card-content")

    def set_artifact(self, artifact: Artifact) -> None:
        """Set the artifact to display."""
        self._artifact = artifact
        self._update_display()

    def watch_artifact(self, artifact: Artifact | None) -> None:
        self._update_display()

    def _update_display(self) -> None:
        content = self.query_one("#card-content", Static)
        if self._artifact is None:
            content.update("")
            return

        a = self._artifact
        state_color = {
            ArtifactState.CREATED: "green",
            ArtifactState.MODIFIED: "yellow",
            ArtifactState.DELETED: "red",
        }[a.state]
        state_label = a.state.value

        age = self._age_string(a.timestamp)
        filename = a.path.split("/")[-1].split("\\")[-1]

        lines = [
            f"[dim]┌─[/dim] [yellow]{filename}[/yellow] "
            f"[{state_color}]{state_label}[/{state_color}] "
            f"[dim]{age}[/dim]"
        ]

        if a.state != ArtifactState.DELETED and a.preview:
            preview_lines = a.preview.split("\n")[:3]
            for pl in preview_lines:
                lines.append(f"  [dim]{pl}[/dim]")
            if len(a.preview.split("\n")) > 3:
                lines.append("  [dim]...[/dim]")

        if a.diff_lines:
            lines.append("  [dim]┌─ diff ─────────────────────────────┐[/dim]")
            for dl in a.diff_lines[:5]:
                prefix = dl[0] if dl else " "
                color = "green" if prefix == "+" else "red" if prefix == "-" else "dim"
                lines.append(f"  [{color}]{prefix}[/{color}] [dim]{dl[1:]}[/dim]")
            if len(a.diff_lines) > 5:
                lines.append(f"  [dim]... ({len(a.diff_lines) - 5} more lines)[/dim]")
            lines.append("  [dim]└──────────────────────────────────────┘[/dim]")

        lines.append(
            f"  [bold cyan]jump[/bold cyan]"
            f"[dim]  |  [/dim][bold cyan]diff[/bold cyan]"
            f"[dim]  |  [/dim][bold cyan]copy[/bold cyan]"
        )
        lines.append(
            "[dim]└──────────────────────────────────────────────────────┘[/dim]"
        )

        content.update("\n".join(lines))

    def _age_string(self, dt: datetime.datetime) -> str:
        delta = datetime.datetime.now() - dt
        if delta.total_seconds() < 60:
            return f"{int(delta.total_seconds())}s ago"
        if delta.total_seconds() < 3600:
            return f"{int(delta.total_seconds() / 60)}m ago"
        return f"{int(delta.total_seconds() / 3600)}h ago"
